import type { ActivityLog, Category, Document, Flashcard, PackagePrice, User } from "./types"

export const MOCK_CATEGORIES: Category[] = [
  { id: "cat-1", name: "Toán học", color: "#6366f1" },
  { id: "cat-2", name: "Vật lý", color: "#0ea5e9" },
  { id: "cat-3", name: "Hóa học", color: "#10b981" },
  { id: "cat-4", name: "Lập trình", color: "#f59e0b" },
  { id: "cat-5", name: "Kinh tế", color: "#ef4444" },
  { id: "cat-6", name: "Tiếng Anh", color: "#8b5cf6" },
]

export const MOCK_ADMIN: User = {
  id: "user-admin",
  email: "admin@aistudyhub.com",
  displayName: "Admin System",
  password: "Admin123",
  role: "admin",
  isLocked: false,
  emailVerified: true,
  createdAt: new Date("2026-01-01"),
  loginAttempts: 0,
  lastActive: new Date(),
  storageUsed: 1024 * 1024 * 200,
  storageLimit: 1024 * 1024 * 1024 * 5,
  subscriptionTier: "5+",
  subscriptionExpiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
}

export const MOCK_SUB_ADMIN: User = {
  id: "user-sub-admin",
  email: "subadmin@aistudyhub.com",
  displayName: "Sub Admin",
  password: "SubAdmin123",
  role: "sub-admin",
  isLocked: false,
  emailVerified: true,
  createdAt: new Date("2026-02-01"),
  loginAttempts: 0,
  lastActive: new Date(),
  storageUsed: 1024 * 1024 * 10,
  storageLimit: 1024 * 1024 * 1024,
  subscriptionTier: "5+",
  subscriptionExpiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
}

export const MOCK_USERS: User[] = [
  MOCK_ADMIN,
  MOCK_SUB_ADMIN,
  {
    id: "user-1",
    email: "student@aistudyhub.com",
    displayName: "Demo Student",
    password: "Student123",
    role: "user",
    isLocked: false,
    emailVerified: true,
    createdAt: new Date("2026-03-10"),
    loginAttempts: 0,
    lastActive: new Date("2026-05-26"),
    storageUsed: 1024 * 1024 * 45,
    storageLimit: 1024 * 1024 * 512,
    subscriptionTier: "free",
  },
  {
    id: "user-2",
    email: "anhnv@fpt.edu.vn",
    displayName: "AnhNV",
    password: "User12345",
    role: "user",
    isLocked: false,
    emailVerified: true,
    createdAt: new Date("2026-03-15"),
    loginAttempts: 0,
    lastActive: new Date("2026-05-25"),
    storageUsed: 1024 * 1024 * 120,
    storageLimit: 1024 * 1024 * 512,
    subscriptionTier: "2-4",
    subscriptionExpiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
  },
  {
    id: "user-3",
    email: "locpd@fpt.edu.vn",
    displayName: "LocPD",
    password: "User12345",
    role: "user",
    isLocked: true,
    emailVerified: true,
    createdAt: new Date("2026-04-01"),
    loginAttempts: 5,
    lastActive: new Date("2026-05-20"),
    storageUsed: 1024 * 1024 * 80,
    storageLimit: 1024 * 1024 * 512,
    subscriptionTier: "free",
  },
]

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "doc-1",
    name: "Giải tích 1 - Chương 1.pdf",
    type: "pdf",
    size: "2.4 MB",
    sizeBytes: 2516582,
    uploadedAt: new Date("2026-05-20"),
    uploadedBy: "user-1",
    categoryId: "cat-1",
    subject: "Giải tích",
    status: "ready",
    tags: ["giải tích", "đạo hàm", "tích phân"],
    downloadCount: 15,
    isPublic: true,
    shareStatus: "approved",
    description: "Tài liệu chương 1 môn Giải Tích 1 - Giới hạn và đạo hàm",
  },
  {
    id: "doc-2",
    name: "OOP Java - Slides.pptx",
    type: "pptx",
    size: "5.1 MB",
    sizeBytes: 5348454,
    uploadedAt: new Date("2026-05-22"),
    uploadedBy: "user-1",
    categoryId: "cat-4",
    subject: "Lập trình",
    status: "ready",
    tags: ["java", "OOP"],
    downloadCount: 32,
    isPublic: true,
    shareStatus: "approved",
    description: "Slides bài giảng OOP với Java",
  },
  {
    id: "doc-3",
    name: "Vật lý đại cương - Cơ học.pdf",
    type: "pdf",
    size: "3.8 MB",
    sizeBytes: 3985162,
    uploadedAt: new Date("2026-05-18"),
    uploadedBy: "user-2",
    categoryId: "cat-2",
    subject: "Vật lý",
    status: "ready",
    tags: ["cơ học", "vật lý"],
    downloadCount: 8,
    isPublic: true,
    shareStatus: "approved",
  },
  {
    id: "doc-4",
    name: "English Grammar Advanced.docx",
    type: "docx",
    size: "1.2 MB",
    sizeBytes: 1258291,
    uploadedAt: new Date("2026-05-15"),
    uploadedBy: "user-2",
    categoryId: "cat-6",
    subject: "Tiếng Anh",
    status: "ready",
    tags: ["grammar", "english"],
    downloadCount: 24,
    isPublic: true,
    shareStatus: "approved",
  },
  {
    id: "doc-5",
    name: "Kinh tế vi mô - Chương 3.pdf",
    type: "pdf",
    size: "4.5 MB",
    sizeBytes: 4718592,
    uploadedAt: new Date("2026-05-10"),
    uploadedBy: "user-1",
    categoryId: "cat-5",
    subject: "Kinh tế",
    status: "ready",
    tags: ["kinh tế", "cung cầu"],
    downloadCount: 11,
    isPublic: false,
    shareStatus: "pending",
    shareNote: "Muốn chia sẻ cho cả lớp tham khảo",
  },
  {
    id: "doc-6",
    name: "Hóa hữu cơ - Tổng hợp.pdf",
    type: "pdf",
    size: "3.1 MB",
    sizeBytes: 3251200,
    uploadedAt: new Date("2026-05-25"),
    uploadedBy: "user-2",
    categoryId: "cat-3",
    subject: "Hóa học",
    status: "ready",
    tags: ["hóa hữu cơ", "tổng hợp"],
    downloadCount: 0,
    isPublic: false,
    shareStatus: "pending",
    shareNote: "Tài liệu ôn tập hóa hữu cơ",
  },
]

export const MOCK_ACTIVITY: ActivityLog[] = [
  { id: "log-1", userId: "user-1", action: "Tải lên tài liệu", target: "Giải tích 1 - Chương 1.pdf", timestamp: new Date("2026-05-20T09:30:00") },
  { id: "log-2", userId: "user-1", action: "Tải xuống tài liệu", target: "OOP Java - Slides.pptx", timestamp: new Date("2026-05-21T14:00:00") },
  { id: "log-3", userId: "user-sub-admin", action: "Cập nhật giới hạn lưu trữ", target: "student@aistudyhub.com", timestamp: new Date("2026-05-22T10:15:00") },
]

export const DEFAULT_PACKAGE_PRICES: PackagePrice[] = [
  { id: "pkg-free", name: "Gói Free", tier: "free", price: 0, maxUsers: 5 },
  { id: "pkg-medium", name: "Gói Pro", tier: "2-4", price: 99000, maxUsers: 30 },
  { id: "pkg-large", name: "Gói VIP", tier: "5+", price: 199000, maxUsers: 60 }
]

export const MOCK_FLASHCARDS: Flashcard[] = [
  {
    id: "flashcard-1",
    documentId: "doc-1",
    question: "Nội dung chính của tài liệu Giải tích 1 - Chương 1 là gì?",
    answer: "Giới hạn, đạo hàm và ứng dụng cơ bản trong bài toán tối ưu.",
    createdAt: new Date("2026-05-26T08:00:00"),
    status: "new",
  },
  {
    id: "flashcard-2",
    documentId: "doc-2",
    question: "Khái niệm OOP quan trọng nhất trong Java là gì?",
    answer: "Lập trình hướng đối tượng tập trung vào lớp, đối tượng, kế thừa và đa hình.",
    createdAt: new Date("2026-05-26T08:05:00"),
    status: "learning",
  },
  {
    id: "flashcard-3",
    question: "Tại sao cần tạo flashcard khi học tài liệu?",
    answer: "Flashcard giúp ôn tập nhanh, ghi nhớ điểm chính và củng cố kiến thức qua lặp lại.",
    createdAt: new Date("2026-05-26T08:10:00"),
    status: "mastered",
  },
]
