name: AI StudyHub Local
values:
  - key: baseUrl
    value: 'http://localhost:8080'
    enabled: true
    type: default
  - key: authToken
    value: ''
    enabled: true
    type: secret
  - key: email
    value: ''
    enabled: true
    type: default
  - key: password
    value: ''
    enabled: true
    type: secret
  - key: subject
    value: General
    enabled: true
    type: default
  - key: title
    value: My Document
    enabled: true
    type: default
